name: 更新WakaTime

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          SHOW_LINES_OF_CODE : "False"
          SHOW_PROFILE_VIEWS : "False"
          SHOW_LANGUAGE_PER_REPO : "False"
          SHOW_LOC_CHART : "False"
          SHOW_SHORT_INFO : "False"
          SHOW_PROJECTS : "False"
          SHOW_TOTAL_CODE_TIME : "False"
          SHOW_TIMEZONE: "False"
          SHOW_OS: "False"
          SHOW_TITLE : true
          # SHOW_DAYS_OF_WEEK: true
          SHOW_UPDATED_DATE: "False"
          LOCALE: "zh"
          # UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
